---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: curlimages/curl

params:
  TYPE:
  OTA_SERVICE:

inputs:
  - name: binaries
  - name: version

run:
  path: sh
  args:
    - -exc
    - |
      curl -T binaries/*.bin "${OTA_SERVICE}/api/firmware/${TYPE}/$(cat version/version)"  
