---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: curlimages/curl

params:
  TYPE:
  OTA_SERVICE:

inputs:
  - name: binaries
  - name: version

run:
  path: sh
  args:
    - -exc
    - |
      curl -X PUT \
        --data-binary $(cat binaries/*.bin) \
        "${OTA_SERVICE}/api/firmware?type=${TYPE}&version=$(cat version/version)"  
