// Code generated by counterfeiter. DO NOT EDIT.
package libfakes

import (
	"sync"

	"github.com/petewall/ota-service/v2/lib"
)

type FakeDeviceService struct {
	GetDeviceStub        func(string) (*lib.Device, error)
	getDeviceMutex       sync.RWMutex
	getDeviceArgsForCall []struct {
		arg1 string
	}
	getDeviceReturns struct {
		result1 *lib.Device
		result2 error
	}
	getDeviceReturnsOnCall map[int]struct {
		result1 *lib.Device
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDeviceService) GetDevice(arg1 string) (*lib.Device, error) {
	fake.getDeviceMutex.Lock()
	ret, specificReturn := fake.getDeviceReturnsOnCall[len(fake.getDeviceArgsForCall)]
	fake.getDeviceArgsForCall = append(fake.getDeviceArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetDeviceStub
	fakeReturns := fake.getDeviceReturns
	fake.recordInvocation("GetDevice", []interface{}{arg1})
	fake.getDeviceMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDeviceService) GetDeviceCallCount() int {
	fake.getDeviceMutex.RLock()
	defer fake.getDeviceMutex.RUnlock()
	return len(fake.getDeviceArgsForCall)
}

func (fake *FakeDeviceService) GetDeviceCalls(stub func(string) (*lib.Device, error)) {
	fake.getDeviceMutex.Lock()
	defer fake.getDeviceMutex.Unlock()
	fake.GetDeviceStub = stub
}

func (fake *FakeDeviceService) GetDeviceArgsForCall(i int) string {
	fake.getDeviceMutex.RLock()
	defer fake.getDeviceMutex.RUnlock()
	argsForCall := fake.getDeviceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDeviceService) GetDeviceReturns(result1 *lib.Device, result2 error) {
	fake.getDeviceMutex.Lock()
	defer fake.getDeviceMutex.Unlock()
	fake.GetDeviceStub = nil
	fake.getDeviceReturns = struct {
		result1 *lib.Device
		result2 error
	}{result1, result2}
}

func (fake *FakeDeviceService) GetDeviceReturnsOnCall(i int, result1 *lib.Device, result2 error) {
	fake.getDeviceMutex.Lock()
	defer fake.getDeviceMutex.Unlock()
	fake.GetDeviceStub = nil
	if fake.getDeviceReturnsOnCall == nil {
		fake.getDeviceReturnsOnCall = make(map[int]struct {
			result1 *lib.Device
			result2 error
		})
	}
	fake.getDeviceReturnsOnCall[i] = struct {
		result1 *lib.Device
		result2 error
	}{result1, result2}
}

func (fake *FakeDeviceService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getDeviceMutex.RLock()
	defer fake.getDeviceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDeviceService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ lib.DeviceService = new(FakeDeviceService)
